name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: nl.registry.novps.app
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set env
        shell: bash
        working-directory: .
        run: echo "${GITHUB_REF#refs/*/}" >> ./tag && echo "${GITHUB_SHA}" >> ./commit
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: nl.registry.novps.app/test/simple-pyhon-api:latest,nl.registry.novps.app/test/simple-pyhon-api:${{ env.RELEASE_VERSION }}